site_name: Git

name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

nav:
  - Introduction: index.md
  - Getting Started with Git: getting-started-with-git.md
  - Git Basics: git-basics.md
  - Git Branching: git-branching.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md

theme:
  name: material
  features:
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite

  - pymdownx.snippets

  - admonition

  - pymdownx.details

  - attr_list

  - md_in_html

  - pymdownx.superfences

  - def_list

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - table-reader
