site_name: My Docs

theme:
  name: material
  features:
    - content.code.copy
    - toc.integrate
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite

  - pymdownx.snippets

  - admonition

  - pymdownx.details

  - attr_list

  - md_in_html

  - pymdownx.superfences

  - def_list

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - table-reader
